name: Upload Python Package
on:
  release:
    types: [published]
jobs:
  deploy-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Publish
      run: |
        python -m pip install --upgrade pip wheel
        pip install poetry
        poetry install
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN}}
        poetry publish --build
